cache:
  - "x86_64-6.2.0-release-posix-seh-rt_v5-rev1.7z"
  
environment:
  machine_user: test_user
  machine_pass: Pass@word1
  mingw_url: "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.2.0/threads-posix/seh/x86_64-6.2.0-release-posix-seh-rt_v5-rev1.7z/download"
  mingw_archive: "x86_64-6.2.0-release-posix-seh-rt_v5-rev1.7z"
  mingw_directory: mingw64
  CTEST_OUTPUT_ON_FAILURE: 1  

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE
      
    - BUILD_TYPE: release
      STATIC_LIBRARIES: TRUE
      
install:
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add
  - if not exist "%mingw_archive%" appveyor DownloadFile "%mingw_url%" -FileName "%mingw_archive%"
  - 7z x -y "%mingw_archive%" > nul
    
before_build:
  - set Path=%CD%\%mingw_directory%\bin;%Path%
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - ps: py -3 ./fetch_subprojects.py
  - ps: Get-Command sh.exe -All | Remove-Item
  - ps: new-item -Name build -ItemType directory
  - ps: cd build  
  - cmake .. -G "MinGW Makefiles" -Dbuild_type=%BUILD_TYPE% -Dstatic_libraries=%STATIC_LIBRARIES%

build_script:
  - cmake --build . --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

after_build:
  - cmake --build . --use-stderr --target test
